# Generated by Django 2.2.6 on 2019-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
