# Generated by Django 2.2.6 on 2019-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0004_auto_20191017_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Device',
            name='floor',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
