# Generated by Django 2.2.6 on 2019-10-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0007_map_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='device_pics'),
        ),
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.URLField(default='https://www.ipIoTDevice.com/'),
        ),
    ]
