# Generated by Django 2.2.6 on 2019-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0008_auto_20191022_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Device',
            name='building',
            field=models.TextField(default='Shapiro', max_length=200),
        ),
        migrations.AlterField(
            model_name='Device',
            name='floor',
            field=models.TextField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='Device',
            name='height',
            field=models.TextField(default='0 m', max_length=4),
        ),
        migrations.AlterField(
            model_name='Device',
            name='name',
            field=models.TextField(default='unnamed', max_length=100),
        ),
        migrations.AlterField(
            model_name='Device',
            name='room',
            field=models.TextField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='Device',
            name='type',
            field=models.TextField(default='no type', max_length=100),
        ),
    ]
