# Generated by Django 2.2.6 on 2019-10-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0012_auto_20191029_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Device',
            name='building',
            field=models.CharField(choices=[('Shapiro', 'Schapiro Center for Engineering and Physical Science Research'), ('Uris Hall', 'Uris Hall')], default='Shapiro', max_length=200),
        ),
    ]
