# Generated by Django 2.2.6 on 2019-11-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0014_auto_20191029_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='devicename',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='roomname',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='building',
        ),
        migrations.RemoveField(
            model_name='device',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='building',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.AddField(
            model_name='building',
            name='buildingname',
            field=models.CharField(choices=[('Schapiro', 'Schapiro Center for Engineering and Physical Science Research'), ('Uris Hall', 'Uris Hall')], default='unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='buildingstructure',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='site_plan.Floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='floorname',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='site_plan.Room'),
        ),
        migrations.AddField(
            model_name='floor',
            name='floorstructure',
            field=models.CharField(choices=[('3', '3th Floor'), ('4', '4th Floor'), ('5', '5th Floor'), ('6', '6th Floor'), ('7', '7th Floor'), ('8', '8th Floor'), ('9', '9th Floor'), ('10', '10th Floor')], default='unnamed', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='height',
            field=models.CharField(default='0 m', help_text='Height above floor level', max_length=4),
        ),
    ]
