# Generated by Django 2.2.6 on 2019-10-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0005_auto_20191017_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Device',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
