# Generated by Django 2.2.6 on 2019-10-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0006_auto_20191017_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='Device',
            name='height',
            field=models.CharField(default='0 m', max_length=4),
        ),
    ]
