# Generated by Django 2.2.6 on 2019-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0010_auto_20191028_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Device',
            name='ip',
        ),
        migrations.AlterField(
            model_name='Device',
            name='type',
            field=models.CharField(choices=[('Samsung TV', 'Samsung TV'), ('Router', 'Router')], default='no type', max_length=100),
        ),
    ]
