# Generated by Django 2.2.6 on 2019-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0011_auto_20191029_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Device',
            name='floor',
            field=models.CharField(choices=[('5', '5th Floor')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='Device',
            name='type',
            field=models.CharField(choices=[('Samsung TV', 'Samsung TV'), ('Router', 'Router'), ('Phillips Hue', 'Phillips Hue')], default='no type', max_length=100),
        ),
    ]
