# Generated by Django 2.2.6 on 2019-11-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_plan', '0015_auto_20191118_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='buildingstructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_plan.Floor'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_plan.Room'),
        ),
    ]
